fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    pmlc_keystone: https://github.com/mirantis/pmlc_keystone.git
  symlinks:
    pmlc_keystone: "#{source_dir}"
